package com.termux.app.terminal;

import android.content.Context;

/** Controls toast notifications generated by title updates from background terminal sessions. */
public final class TerminalTitleNotificationSettings {
    private static final String PREFS = "terminal_ui";
    private static final String KEY_BACKGROUND_TITLE_NOTIFICATIONS = "background_title_notifications";

    private TerminalTitleNotificationSettings() {}

    public static boolean isEnabled(Context context) {
        return context.getSharedPreferences(PREFS, Context.MODE_PRIVATE)
            .getBoolean(KEY_BACKGROUND_TITLE_NOTIFICATIONS, false);
    }

    public static void setEnabled(Context context, boolean enabled) {
        context.getSharedPreferences(PREFS, Context.MODE_PRIVATE).edit()
            .putBoolean(KEY_BACKGROUND_TITLE_NOTIFICATIONS, enabled).apply();
    }
}
